trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  - script: |
      terraform init
      terraform validate
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
    displayName: "Deploy Sentinel Configuration"
